import { db } from '@/backend/database/client'

export function getProjectRevisionEditorState(projectId: string, creatorId: string) {
  return db.project.findFirst({
    where: { id: projectId, creatorId },
    select: {
      id: true,
      creatorId: true,
      status: true,
      version: true,
      title: true,
      summary: true,
      description: true,
      stage: true,
      purpose: true,
      audience: true,
      typeTags: true,
      seekingTags: true,
      platforms: true,
      externalUrl: true,
      groupType: true,
      groupContact: true,
      groupAccessMode: true,
      allowIshJoinGroup: true,
      revisions: {
        where: { status: { in: ['PENDING', 'REJECTED'] } },
        orderBy: [{ version: 'desc' }, { submittedAt: 'desc' }],
        take: 1,
        select: {
          id: true,
          version: true,
          status: true,
          rejectionReason: true,
          title: true,
          summary: true,
          description: true,
          stage: true,
          purpose: true,
          audience: true,
          typeTags: true,
          seekingTags: true,
          platforms: true,
          externalUrl: true,
          groupType: true,
          groupContact: true,
          groupAccessMode: true,
          allowIshJoinGroup: true,
          submittedAt: true,
          reviewedAt: true,
        },
      },
    },
  })
}
